$("#img1t").click(function(){
    $("#img1").addClass('active');
    $("#img2").removeClass('active');
    $("#img3").removeClass('active');
    $("#img4").removeClass('active');
});
$("#img2t").click(function(){
    $("#img1").removeClass('active');
    $("#img2").addClass('active');
    $("#img3").removeClass('active');
    $("#img4").removeClass('active');
});
$("#img3t").click(function(){
    $("#img1").removeClass('active');
    $("#img2").removeClass('active');
    $("#img3").addClass('active');
    $("#img4").removeClass('active');
});
$("#img4t").click(function(){
    $("#img1").removeClass('active');
    $("#img2").removeClass('active');
    $("#img3").removeClass('active');
    $("#img4").addClass('active');
});

$("#thumbnail1").click(function(){
    $("#slide1").addClass('active');
    $("#slide2").removeClass('active');
    $("#slide3").removeClass('active');
    $("#slide4").removeClass('active');
    $("#slide5").removeClass('active');
});
$("#thumbnail2").click(function(){
    $("#slide1").removeClass('active');
    $("#slide2").addClass('active');
    $("#slide3").removeClass('active');
    $("#slide4").removeClass('active');
    $("#slide5").removeClass('active');
});
$("#thumbnail3").click(function(){
    $("#slide1").removeClass('active');
    $("#slide2").removeClass('active');
    $("#slide3").addClass('active');
    $("#slide4").removeClass('active');
    $("#slide5").removeClass('active');
});
$("#thumbnail4").click(function(){
    $("#slide1").removeClass('active');
    $("#slide2").removeClass('active');
    $("#slide3").removeClass('active');
    $("#slide4").addClass('active');
    $("#slide5").removeClass('active');
});

